version: 2.1

orbs:
  gh: circleci/github-cli@2.4.0

commands:
  setup-audius-ctl:
    description: Checkout and install audius-ctl built in previous job
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Uninstall any existing audius-ctl binary
          command: |
            make uninstall
      - run:
          name: Install audius-ctl
          command: |
            make install
      - run:
          name: 'Install self-signed ssl certificate for devnet.audius-d'
          command: |
            sudo cp dev-tools/tls/devnet-cert.pem /usr/local/share/ca-certificates/devnet.audius-d.crt
            sudo update-ca-certificates
  docker-login:
    steps:
      - run:
          name: Docker login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  docker-logout:
    steps:
      - run:
          when: always
          name: Log out of Docker
          command: docker logout
  install-crane:
    steps:
      - run:
          name: Install Crane
          command: |
            VERSION=v0.20.2
            OS=Linux
            ARCH=x86_64
            curl -sL "https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz" > go-containerregistry.tar.gz
            tar -zxvf go-containerregistry.tar.gz -C $HOME/bin/ crane
  install-buf:
    steps:
      - run:
          name: Install Buf
          command: |
            VERSION=1.49.0
            OS=$(uname -s)
            ARCH=$(uname -m)
            
            curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-${OS}-${ARCH}" -o $HOME/bin/buf
            
            chmod +x $HOME/bin/buf

            echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            
            buf --version
  push-buf:
    steps:
      - run:
          name: Push Buf
          command: |
            echo ${BUF_TOKEN} | buf registry login --token-stdin
            cd pkg/core && buf push --create --git-metadata


jobs:
  build-audiusd-bin:
    docker:
      - image: cimg/go:1.23
    resource_class: xlarge
    environment:
      GOCACHE: /home/circleci/.cache/go-build
      GOMODCACHE: /home/circleci/go/pkg/mod
      GOMAXPROCS: "8"
      GOFLAGS: "-trimpath -mod=readonly -p=8"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-deps-v1-{{ checksum "Makefile" }}
            - go-deps-v1-
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
            - go-build-v1-{{ .Branch }}-{{ checksum "go.sum" }}
            - go-build-v1-{{ .Branch }}
      - install-buf
      - push-buf
      - run:
          command: |
            make install-go-deps
            go mod download
      - save_cache:
          key: go-deps-v1-{{ checksum "Makefile" }}
          paths:
            - /home/circleci/go/bin
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Build audiusd binaries
          command: |
            make bin/audiusd-x86_64-linux
            make bin/audiusd-arm64-linux
      - save_cache:
          key: go-build-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.cache/go-build
      - persist_to_workspace:
          root: ./
          paths:
            - bin/audiusd-x86_64-linux
            - bin/audiusd-arm64-linux

  build-and-test-audiusd-amd64:
    machine: true
    resource_class: audiusproject/gcp-n2-standard-4
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - docker-login
      - run:
          name: Build amd64-linux images
          command: |
            DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build \
              --target prod \
              --build-arg GIT_SHA=${CIRCLE_SHA1} \
              --build-arg PREBUILT_BINARY=bin/audiusd-x86_64-linux \
              -t audius/audiusd:${CIRCLE_SHA1}-amd64 \
              -f ./cmd/audiusd/Dockerfile.ci ./
            docker push audius/audiusd:${CIRCLE_SHA1}-amd64
            
            DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build \
              --target test \
              --build-arg GIT_SHA=${CIRCLE_SHA1} \
              --build-arg PREBUILT_BINARY=bin/audiusd-x86_64-linux \
              -t audius/audiusd:${CIRCLE_SHA1}-test \
              -f ./cmd/audiusd/Dockerfile.ci ./
      - run:
          name: Run (unit) mediorum tests
          command: |
            AUDIUSD_IMAGE=audius/audiusd:${CIRCLE_SHA1}-amd64 \
            TEST_IMAGE=audius/audiusd:${CIRCLE_SHA1}-test \
            TTY_FLAG="--no-TTY" make mediorum-test
      - run:
          name: Run (integration) core tests
          command: |
            AUDIUSD_IMAGE=audius/audiusd:${CIRCLE_SHA1}-amd64 \
            TEST_IMAGE=audius/audiusd:${CIRCLE_SHA1}-test \
            TTY_FLAG="--no-TTY" make core-test
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Push amd64-linux image
                command: docker push audius/audiusd:${CIRCLE_SHA1}-amd64

  build-audiusd-arm64:
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - docker-login
      - run:
          name: Build arm64-linux image
          command: |
            DOCKER_DEFAULT_PLATFORM=linux/arm64 docker build \
              --target prod \
              --build-arg GIT_SHA=${CIRCLE_SHA1} \
              --build-arg PREBUILT_BINARY=bin/audiusd-arm64-linux \
              -t audius/audiusd:${CIRCLE_SHA1}-arm64 \
              -f ./cmd/audiusd/Dockerfile.ci ./
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Push arm64-linux image
                command: docker push audius/audiusd:${CIRCLE_SHA1}-arm64

  push-audiusd-manifest:
    docker:
      - image: cimg/base:current
    steps:
      - docker-login
      - run:
          name: Create manifest
          command: |
            docker manifest create audius/audiusd:${CIRCLE_SHA1} \
              audius/audiusd:${CIRCLE_SHA1}-amd64 \
              audius/audiusd:${CIRCLE_SHA1}-arm64
            docker manifest push audius/audiusd:${CIRCLE_SHA1}
      - docker-logout

  deploy-audiusd-staging:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - docker-login
      - install-crane
      - run:
          name: Release audiusd to staging
          command: |
            crane copy "audius/audiusd:${CIRCLE_SHA1}" "audius/audiusd:prerelease"

  deploy-audiusd-foundation:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - docker-login
      - install-crane
      - run:
          name: Release audiusd to foundation
          command: |
            crane copy "audius/audiusd:${CIRCLE_SHA1}" "audius/audiusd:edge"

  deploy-audiusd-sps:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - docker-login
      - install-crane
      - run:
          name: Release audiusd to sps
          command: |
            crane copy "audius/audiusd:${CIRCLE_SHA1}" "audius/audiusd:current"

  publish-audiusd-release:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - gh/setup
      - run:
          name: Create Release
          command: |
            echo "## Docker Images" > release_notes.md
            echo "- \`audius/audiusd:${CIRCLE_SHA1}\` (amd64, arm64)" >> release_notes.md
            echo "" >> release_notes.md
            
            gh api repos/{owner}/{repo}/releases/generate-notes \
              -F tag_name="audiusd@${CIRCLE_SHA1}" \
              -F target_commitish="${CIRCLE_SHA1}" \
              --jq .body >> release_notes.md

            # Create the release with binaries
            gh release create "audiusd@${CIRCLE_SHA1}" \
              --title "audiusd ${CIRCLE_SHA1}" \
              --notes-file release_notes.md \
              bin/audiusd-x86_64-linux \
              bin/audiusd-arm64-linux

workflows:
  audiusd:
    jobs:
      - build-audiusd-bin
      - build-and-test-audiusd-amd64:
          context: DockerHub
          requires:
            - build-audiusd-bin
      - build-audiusd-arm64:
          context: DockerHub
          requires:
            - build-audiusd-bin
          filters:
            branches:
              only:
                - main
      - push-audiusd-manifest:
          context: DockerHub
          requires:
            - build-and-test-audiusd-amd64
            - build-audiusd-arm64
          filters:
            branches:
              only:
                - main
      - deploy-audiusd-staging-trigger:
          requires:
            - push-audiusd-manifest
          type: approval
          filters:
            branches:
              only:
                - main
      - deploy-audiusd-staging:
          context: DockerHub
          requires:
            - deploy-audiusd-staging-trigger
          filters:
            branches:
              only:
                - main
      - publish-audiusd-release-trigger:
          requires:
            - deploy-audiusd-staging
          type: approval
      - publish-audiusd-release:
          context:
            - DockerHub
            - github
          requires:
            - publish-audiusd-release-trigger
          filters:
            branches:
              only:
                - main
      - deploy-audiusd-foundation-trigger:
          requires:
            - deploy-audiusd-staging
          type: approval
      - deploy-audiusd-foundation:
          context: DockerHub
          requires:
            - deploy-audiusd-foundation-trigger
      - deploy-audiusd-sps-trigger:
          requires:
            - publish-audiusd-release
          type: approval
      - deploy-audiusd-sps:
          context: DockerHub
          requires:
            - deploy-audiusd-sps-trigger
