# Do not expose any ports in this file to allow running multiple tests and e2e dev at the same time

x-logging: &default-logging
  options:
    max-size: '50m'
    max-file: '3'
  driver: json-file

networks:
  test-net:
    name: audiusd-test-net

services:
  ingress:
    image: nginx
    logging: *default-logging
    volumes:
      - ./compose/nginx_ingress_test.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - 'audiusd-test-1:host-gateway'
      - 'audiusd-test-2:host-gateway'
      - 'audiusd-test-3:host-gateway'
      - 'audiusd-test-4:host-gateway'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://audiusd-1/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 80:80
    profiles:
      - mediorum
      - core-tests
    depends_on:
      audiusd-1:
        condition: service_started
      audiusd-2:
        condition: service_started
      audiusd-3:
        condition: service_started
      audiusd-4:
        condition: service_started
    networks:
      - test-net

  eth-ganache:
    image: audius/eth-ganache:latest
    command: bash /tmp/scripts/eth-ganache.sh
    volumes:
      - ./compose/scripts/eth-ganache.sh:/tmp/scripts/eth-ganache.sh
    logging: *default-logging
    deploy:
      mode: global
    profiles:
      - mediorum
      - core-tests
    networks:
      - test-net

  audiusd-1:
    image: ${AUDIUSD_IMAGE:-audius/audiusd:local}
    env_file:
      - ./compose/env/audiusd-test-1.docker.env
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost/health-check' ]
      interval: 10s
      start_period: 60s
      timeout: 5s
    profiles:
      - mediorum
      - core-tests
    ports:
      - "26656:26656"
    networks:
      - test-net

  audiusd-2:
    image: ${AUDIUSD_IMAGE:-audius/audiusd:local}
    env_file:
      - ./compose/env/audiusd-test-2.docker.env
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost/health-check' ]
      interval: 10s
      start_period: 60s
      timeout: 5s
    profiles:
      - mediorum
      - core-tests
    ports:
      - "26666:26656"
    networks:
      - test-net

  audiusd-3:
    image: ${AUDIUSD_IMAGE:-audius/audiusd:local}
    env_file:
      - ./compose/env/audiusd-test-3.docker.env
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost/health-check' ]
      interval: 10s
      start_period: 60s
      timeout: 5s
    profiles:
      - mediorum
      - core-tests
    ports:
      - "26676:26656"
    networks:
      - test-net

  audiusd-4:
    image: ${AUDIUSD_IMAGE:-audius/audiusd:local}
    env_file:
      - ./compose/env/audiusd-test-4.docker.env
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost/health-check' ]
      interval: 10s
      start_period: 60s
      timeout: 5s
    profiles:
      - mediorum
      - core-tests
    ports:
      - "26686:26656"
    networks:
      - test-net

  test-core:
    image: ${TEST_IMAGE:-audius/audiusd:test}
    command: go test -v -count=1 -timeout=60s ./pkg/core/...
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    logging: *default-logging
    environment:
      discoveryOneGRPC: audiusd-1:50051
      discoveryOneJRPC: http://audiusd-1:26657
      discoveryOneOAPI: audiusd-1:26659
      contentOneGRPC: audiusd-2:50051
      contentOneJRPC: http://audiusd-2:26657
      contentOneOAPI: audiusd-2:26659
      contentTwoGRPC: audiusd-3:50051
      contentTwoJRPC: http://audiusd-3:26657
      contentTwoOAPI: audiusd-3:26659
      contentThreeGRPC: audiusd-4:50051
      contentThreeJRPC: http://audiusd-4:26657
      contentThreeOAPI: audiusd-4:26659
    profiles:
      - core-tests
    depends_on:
      ingress:
        condition: service_healthy
      audiusd-1:
        condition: service_started
      audiusd-2:
        condition: service_started
      audiusd-3:
        condition: service_started
      audiusd-4:
        condition: service_started
      eth-ganache:
        condition: service_healthy
    networks:
      - test-net

  test-mediorum-unittests:
    image: ${TEST_IMAGE:-audius/audiusd:test}
    command: go test -v -count=1 -timeout=60s ./pkg/mediorum/...
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    logging: *default-logging
    environment:
      NETWORK: test
      dbUrlTemplate: 'postgres://postgres:postgres@localhost:5432/m%d'
      dbUrl: 'postgres://postgres:postgres@localhost:5432/mediorum_test'
    profiles:
      - mediorum-unittests
